### ISSUE TITLE
Redmine 2.6.0

### ISSUE THREAD

**Issue by elalemanyo** [samchen2009/ekanban#84]
Hi,
I will like to use your redmine plugin but I am using version 2.6.0 and your plugin is not working with this version. Are you going to do an update to support the new redmine version?

Thanks!

**Comment by prmartinuk** [comment]
It is working happily for me on Redmine 2.6.1.
Is it giving any error messages or any hints to tell you what is wrong?

**Comment by louisfischer** [comment]
It is not working for me on  2.6.1. This is the error

Started GET "/redmine/projects/application-development/kanbans" for 127.0.0.1 at 2015-02-19 08:34:17 -0600
Processing by KanbansController#index as HTML
  Parameters: {"project_id"=>"application-development"}
  Current user: ogi8381 (id=5)
  Rendered plugins/ekanban/app/views/kanbans/index.html.haml within layouts/base (6.0ms)
Completed 500 Internal Server Error in 21.0ms

ActionView::Template::Error (undefined method `id' for nil:NilClass):
    2:   %span Your current wip:
    3:   = link_to "#{User.current.wip} ", my_page_path(), :id => "my-wip"
    4:   %span  Limit:
    5:   = link_to "#{User.current.wip_limit} ", edit_user_path(User.current.id), :id => "my-wip-limit"
    6:   = link_to l(:label_kanban_new), new_project_kanban_path(@project.id), :class => 'icon icon-add'
    7: %h2 Kanbans
    8: 
  plugins/ekanban/lib/ekanban/user_patch.rb:36:in`wip_limit'
  plugins/ekanban/app/views/kanbans/index.html.haml:5:in `_plugins_ekanban_app_views_kanbans_index_html_haml___783235208_71241156'
  actionpack (3.2.21) lib/action_view/template.rb:145:in`block in render'
  activesupport (3.2.21) lib/active_support/notifications.rb:125:in `instrument'
  actionpack (3.2.21) lib/action_view/template.rb:143:in`render'
  actionpack (3.2.21) lib/action_view/renderer/template_renderer.rb:47:in `block (2 levels) in render_template'
  actionpack (3.2.21) lib/action_view/renderer/abstract_renderer.rb:38:in`block in instrument'
  activesupport (3.2.21) lib/active_support/notifications.rb:123:in `block in instrument'
  activesupport (3.2.21) lib/active_support/notifications/instrumenter.rb:20:in`instrument'
  activesupport (3.2.21) lib/active_support/notifications.rb:123:in `instrument'
  actionpack (3.2.21) lib/action_view/renderer/abstract_renderer.rb:38:in`instrument'
  actionpack (3.2.21) lib/action_view/renderer/template_renderer.rb:46:in `block in render_template'
  actionpack (3.2.21) lib/action_view/renderer/template_renderer.rb:54:in`render_with_layout'
  actionpack (3.2.21) lib/action_view/renderer/template_renderer.rb:45:in `render_template'
  actionpack (3.2.21) lib/action_view/renderer/template_renderer.rb:18:in`render'
  actionpack (3.2.21) lib/action_view/renderer/renderer.rb:36:in `render_template'
  actionpack (3.2.21) lib/action_view/renderer/renderer.rb:17:in`render'
  actionpack (3.2.21) lib/abstract_controller/rendering.rb:110:in `_render_template'
  actionpack (3.2.21) lib/action_controller/metal/streaming.rb:225:in`_render_template'
  actionpack (3.2.21) lib/abstract_controller/rendering.rb:103:in `render_to_body'
  actionpack (3.2.21) lib/action_controller/metal/renderers.rb:28:in`render_to_body'
  actionpack (3.2.21) lib/action_controller/metal/compatibility.rb:50:in `render_to_body'
  actionpack (3.2.21) lib/abstract_controller/rendering.rb:88:in`render'
  actionpack (3.2.21) lib/action_controller/metal/rendering.rb:16:in `render'
  actionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:40:in`block (2 levels) in render'
  activesupport (3.2.21) lib/active_support/core_ext/benchmark.rb:5:in `block in ms'
  C:/Bitnami/redmine-2.6.1-0/ruby/lib/ruby/2.0.0/benchmark.rb:296:in`realtime'
  activesupport (3.2.21) lib/active_support/core_ext/benchmark.rb:5:in `ms'
  actionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:40:in`block in render'
  actionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:83:in `cleanup_view_runtime'
  activerecord (3.2.21) lib/active_record/railties/controller_runtime.rb:24:in`cleanup_view_runtime'
  actionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:39:in `render'
  actionpack (3.2.21) lib/action_controller/metal/implicit_render.rb:10:in`default_render'
  actionpack (3.2.21) lib/action_controller/metal/mime_responds.rb:196:in `respond_to'
  plugins/ekanban/app/controllers/kanbans_controller.rb:52:in`index'
  actionpack (3.2.21) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (3.2.21) lib/abstract_controller/base.rb:167:in`process_action'
  actionpack (3.2.21) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (3.2.21) lib/abstract_controller/callbacks.rb:18:in`block in process_action'
  activesupport (3.2.21) lib/active_support/callbacks.rb:480:in `_run__207182439__process_action__357439590__callbacks'
  activesupport (3.2.21) lib/active_support/callbacks.rb:405:in`__run_callback'
  activesupport (3.2.21) lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
  activesupport (3.2.21) lib/active_support/callbacks.rb:81:in`run_callbacks'
  actionpack (3.2.21) lib/abstract_controller/callbacks.rb:17:in `process_action'
  actionpack (3.2.21) lib/action_controller/metal/rescue.rb:29:in`process_action'
  actionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
  activesupport (3.2.21) lib/active_support/notifications.rb:123:in`block in instrument'
  activesupport (3.2.21) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (3.2.21) lib/active_support/notifications.rb:123:in`instrument'
  actionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
  actionpack (3.2.21) lib/action_controller/metal/params_wrapper.rb:207:in`process_action'
  activerecord (3.2.21) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (3.2.21) lib/abstract_controller/base.rb:121:in`process'
  actionpack (3.2.21) lib/abstract_controller/rendering.rb:45:in `process'
  actionpack (3.2.21) lib/action_controller/metal.rb:203:in`dispatch'
  actionpack (3.2.21) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
  actionpack (3.2.21) lib/action_controller/metal.rb:246:in`block in action'
  actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:73:in `call'
  actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:73:in`dispatch'
  actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:36:in `call'
  journey (1.0.4) lib/journey/router.rb:68:in`block in call'
  journey (1.0.4) lib/journey/router.rb:56:in `each'
  journey (1.0.4) lib/journey/router.rb:56:in`call'
  actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:608:in `call'
  rack-openid (1.4.1) lib/rack/openid.rb:99:in`call'
  request_store (1.0.5) lib/request_store/middleware.rb:9:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/best_standards_support.rb:17:in`call'
  rack (1.4.5) lib/rack/etag.rb:23:in `call'
  rack (1.4.5) lib/rack/conditionalget.rb:25:in`call'
  actionpack (3.2.21) lib/action_dispatch/middleware/head.rb:14:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/params_parser.rb:21:in`call'
  actionpack (3.2.21) lib/action_dispatch/middleware/flash.rb:242:in `call'
  rack (1.4.5) lib/rack/session/abstract/id.rb:210:in`context'
  rack (1.4.5) lib/rack/session/abstract/id.rb:205:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/cookies.rb:341:in`call'
  activerecord (3.2.21) lib/active_record/query_cache.rb:64:in `call'
  activerecord (3.2.21) lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in`call'
  actionpack (3.2.21) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
  activesupport (3.2.21) lib/active_support/callbacks.rb:405:in`_run__904217407__call__13115359__callbacks'
  activesupport (3.2.21) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.21) lib/active_support/callbacks.rb:385:in`_run_call_callbacks'
  activesupport (3.2.21) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.21) lib/action_dispatch/middleware/callbacks.rb:27:in`call'
  actionpack (3.2.21) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/debug_exceptions.rb:16:in`call'
  actionpack (3.2.21) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  railties (3.2.21) lib/rails/rack/logger.rb:32:in`call_app'
  railties (3.2.21) lib/rails/rack/logger.rb:16:in `block in call'
  activesupport (3.2.21) lib/active_support/tagged_logging.rb:22:in`tagged'
  railties (3.2.21) lib/rails/rack/logger.rb:16:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/request_id.rb:22:in`call'
  rack (1.4.5) lib/rack/methodoverride.rb:21:in `call'
  rack (1.4.5) lib/rack/runtime.rb:17:in`call'
  activesupport (3.2.21) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  rack (1.4.5) lib/rack/lock.rb:15:in`call'
  actionpack (3.2.21) lib/action_dispatch/middleware/static.rb:83:in `call'
  rack-cache (1.2) lib/rack/cache/context.rb:136:in`forward'
  rack-cache (1.2) lib/rack/cache/context.rb:245:in `fetch'
  rack-cache (1.2) lib/rack/cache/context.rb:185:in`lookup'
  rack-cache (1.2) lib/rack/cache/context.rb:66:in `call!'
  rack-cache (1.2) lib/rack/cache/context.rb:51:in`call'
  railties (3.2.21) lib/rails/engine.rb:484:in `call'
  railties (3.2.21) lib/rails/application.rb:231:in`call'
  railties (3.2.21) lib/rails/railtie/configurable.rb:30:in `method_missing'
  rack (1.4.5) lib/rack/urlmap.rb:64:in`block in call'
  rack (1.4.5) lib/rack/urlmap.rb:49:in `each'
  rack (1.4.5) lib/rack/urlmap.rb:49:in`call'
  thin-1.6.1-x86 (mingw32) lib/thin/connection.rb:82:in `block in pre_process'
  thin-1.6.1-x86 (mingw32) lib/thin/connection.rb:80:in`catch'
  thin-1.6.1-x86 (mingw32) lib/thin/connection.rb:80:in `pre_process'
  thin-1.6.1-x86 (mingw32) lib/thin/connection.rb:55:in`process'
  thin-1.6.1-x86 (mingw32) lib/thin/connection.rb:41:in `receive_data'
  eventmachine-1.0.3-x86 (mingw32) lib/eventmachine.rb:187:in`run_machine'
  eventmachine-1.0.3-x86 (mingw32) lib/eventmachine.rb:187:in `run'
  thin-1.6.1-x86 (mingw32) lib/thin/backends/base.rb:73:in`start'
  thin-1.6.1-x86 (mingw32) lib/thin/server.rb:162:in `start'
  thin-1.6.1-x86 (mingw32) lib/thin/controllers/controller.rb:87:in`start'
  thin-1.6.1-x86 (mingw32) lib/thin/runner.rb:200:in `run_command'
  thin-1.6.1-x86 (mingw32) lib/thin/runner.rb:156:in`run!'
  thin-1.6.1-x86 (mingw32) bin/thin:6:in `<top (required)>'
  bin/thin:16:in`load'
  bin/thin:16:in `<main>'

**Comment by prmartinuk** [comment]
@louisfischer Are you doing a new installation of ekanban? If so have you added the custom field "WIP limit" to the Redmine users (using 'Administratoion' -> 'Custom fields' -> 'User')?

**Comment by maximus-dv10** [comment]
Not working in Redmine 2.6.6 

Failed on saving issues:

```
NoMethodError (undefined method `wip' for nil:NilClass):
  app/controllers/issues_controller.rb:481:in `block in save_issue_with_child_records'
  app/controllers/issues_controller.rb:469:in `save_issue_with_child_records'
  app/controllers/issues_controller.rb:188:in `update'
```
